import type { MarketplaceProduct, MarketplaceProductDetail } from "../marketplace-core.js";

export const marketplaceFixtures: readonly MarketplaceProduct[] = [
  {
    id: "arete-blue-dream",
    vendorId: "arete",
    vendorName: "Arete",
    vendorFaviconUrl: "https://example.com/arete.ico",
    strainName: "Blue Dream",
    lineage: "sativa_leaning_hybrid",
    totalThcDisplay: 27.49,
    rating: 4.7,
    reviewCount: 182,
    variants: [
      {
        id: "blue-3.5",
        grams: 3.5,
        sourceWeightLabel: "3.5g",
        currentPrice: 25,
        originalPrice: 30,
        pricePerGram: 7.142857,
        inStock: true,
        productUrl: "https://example.com/blue-dream?variant=3.5",
        imageUrl: "https://example.com/blue-dream-3.5.jpg",
        coa: { id: "coa-blue-3.5", kind: "coa", url: "https://example.com/blue-3.5.pdf", format: "pdf" },
      },
      {
        id: "blue-14",
        grams: 14,
        sourceWeightLabel: "14g",
        currentPrice: 72,
        originalPrice: 90,
        pricePerGram: 5.142857,
        inStock: true,
        productUrl: "https://example.com/blue-dream?variant=14",
        imageUrl: "https://example.com/blue-dream-14.jpg",
        coa: { id: "coa-blue-14", kind: "coa", url: "https://example.com/blue-14.pdf", format: "pdf" },
        terpeneDocument: { id: "terp-blue-14", kind: "terpene", url: "https://example.com/blue-14.png", format: "image" },
      },
      {
        id: "blue-28",
        grams: 28,
        sourceWeightLabel: "28g",
        currentPrice: 144,
        pricePerGram: 5.142857,
        inStock: true,
        productUrl: "https://example.com/blue-dream?variant=28",
      },
    ],
  },
  {
    id: "holy-city-kosmic-kush",
    vendorId: "holy-city",
    vendorName: "Holy City Farms",
    strainName: "Kosmic Kush",
    lineage: "indica",
    totalThcDisplay: 31.1,
    rating: 4.9,
    reviewCount: 54,
    variants: [
      {
        id: "kosmic-7",
        grams: 7,
        sourceWeightLabel: "7g",
        currentPrice: 42,
        pricePerGram: 6,
        inStock: true,
        productUrl: "https://example.com/kosmic-kush/7",
      },
      {
        id: "kosmic-14",
        grams: 14,
        sourceWeightLabel: "14g",
        currentPrice: 75,
        pricePerGram: 5.357142,
        inStock: true,
        productUrl: "https://example.com/kosmic-kush/14",
      },
    ],
  },
  {
    id: "wnc-pineapple-express",
    vendorId: "wnc",
    vendorName: "WNC CBD",
    strainName: "Pineapple Express",
    lineage: "hybrid",
    totalThcDisplay: null,
    variants: [
      {
        id: "pineapple-3.5",
        grams: 3.5,
        sourceWeightLabel: "Eighth",
        currentPrice: 20,
        pricePerGram: 5.714285,
        inStock: true,
        productUrl: "https://example.com/pineapple-express",
      },
    ],
  },
  {
    id: "lucky-elk-jack-herer",
    vendorId: "lucky-elk",
    vendorName: "Lucky Elk",
    strainName: "Jack Herer",
    lineage: "sativa",
    totalThcDisplay: 22,
    rating: 4.3,
    reviewCount: 9,
    variants: [
      {
        id: "jack-14",
        grams: 14,
        sourceWeightLabel: "Half ounce",
        currentPrice: 70,
        pricePerGram: 5,
        inStock: true,
        productUrl: "https://example.com/jack-herer",
      },
    ],
  },
  {
    id: "black-tie-nightshade",
    vendorId: "black-tie",
    vendorName: "Black Tie CBD",
    strainName: "Nightshade",
    lineage: "indica_leaning_hybrid",
    totalThcDisplay: 29,
    variants: [
      {
        id: "nightshade-7",
        grams: 7,
        sourceWeightLabel: "7 grams",
        currentPrice: 39,
        originalPrice: 38,
        pricePerGram: 5.571428,
        inStock: true,
        productUrl: "https://example.com/nightshade",
      },
    ],
  },
  {
    id: "green-unicorn-sunrise",
    vendorId: "green-unicorn",
    vendorName: "Green Unicorn Farms",
    strainName: "Sunrise",
    lineage: "unknown",
    totalThcDisplay: 18.4,
    variants: [
      {
        id: "sunrise-3.5",
        grams: 3.5,
        sourceWeightLabel: "3.5g",
        currentPrice: 18,
        pricePerGram: 5.142857,
        inStock: true,
        productUrl: "https://example.com/sunrise",
      },
    ],
  },
  {
    id: "five-leaf-diesel",
    vendorId: "five-leaf",
    vendorName: "Five Leaf Wellness",
    strainName: "Diesel Fog",
    lineage: "sativa_leaning_hybrid",
    totalThcDisplay: 24,
    variants: [
      {
        id: "diesel-invalid",
        grams: 0,
        sourceWeightLabel: "Unknown",
        currentPrice: 0,
        pricePerGram: 0,
        inStock: true,
        productUrl: "https://example.com/diesel",
      },
    ],
  },
];

export const details: Readonly<Record<string, MarketplaceProductDetail>> = {
  "arete-blue-dream": {
    productId: "arete-blue-dream",
    imageUrl: "https://example.com/blue-dream.jpg",
    effects: ["calm", "creative", "uplifted"],
    growEnvironment: "indoor",
  },
  "holy-city-kosmic-kush": {
    productId: "holy-city-kosmic-kush",
    effects: ["relaxed", "sleepy"],
    growEnvironment: "greenhouse",
  },
};
